import * as auth from "./auth/index";
export { auth };
import * as contacts from "./contacts/index";
export { contacts };
import * as messages from "./messages/index";
export { messages };
import * as updates from "./updates/index";
export { updates };
import * as photos from "./photos/index";
export { photos };
import * as upload from "./upload/index";
export { upload };
import * as help from "./help/index";
export { help };
import * as account from "./account/index";
export { account };
import * as channels from "./channels/index";
export { channels };
import * as payments from "./payments/index";
export { payments };
import * as phone from "./phone/index";
export { phone };
import * as stats from "./stats/index";
export { stats };
import * as stickers from "./stickers/index";
export { stickers };
import * as users from "./users/index";
export { users };
import * as chatlists from "./chatlists/index";
export { chatlists };
import * as bots from "./bots/index";
export { bots };
import * as stories from "./stories/index";
export { stories };
import * as premium from "./premium/index";
export { premium };
import * as smsjobs from "./smsjobs/index";
export { smsjobs };
import * as fragment from "./fragment/index";
export { fragment };
import * as langpack from "./langpack/index";
export { langpack };
import * as folders from "./folders/index";
export { folders };
export * from "./InvokeAfterMsg";
export * from "./InvokeAfterMsgs";
export * from "./InitConnection";
export * from "./InvokeWithLayer";
export * from "./InvokeWithoutUpdates";
export * from "./InvokeWithMessagesRange";
export * from "./InvokeWithTakeout";
export * from "./InvokeWithBusinessConnection";
export * from "./InvokeWithGooglePlayIntegrity";
export * from "./InvokeWithApnsSecret";
export * from "./InvokeWithReCaptcha";
export * from "./ReqPq";
export * from "./ReqPqMulti";
export * from "./ReqDHParams";
export * from "./SetClientDHParams";
export * from "./DestroyAuthKey";
export * from "./RpcDropAnswer";
export * from "./GetFutureSalts";
export * from "./Ping";
export * from "./PingDelayDisconnect";
export * from "./DestroySession";